-- MySQL Script generated by MySQL Workbench
-- 06/17/17 14:29:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema homework_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `homework_db` ;

-- -----------------------------------------------------
-- Schema homework_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homework_db` DEFAULT CHARACTER SET utf8 ;
USE `homework_db` ;

-- -----------------------------------------------------
-- Table `homework_db`.`developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homework_db`.`developers` ;

CREATE TABLE IF NOT EXISTS `homework_db`.`developers` (
  `developer_id` INT NOT NULL AUTO_INCREMENT,
  `developer_name` VARCHAR(45) NULL,
  PRIMARY KEY (`developer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework_db`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homework_db`.`skills` ;

CREATE TABLE IF NOT EXISTS `homework_db`.`skills` (
  `skill_id` INT NOT NULL AUTO_INCREMENT,
  `skill_name` VARCHAR(45) NULL,
  PRIMARY KEY (`skill_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework_db`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homework_db`.`projects` ;

CREATE TABLE IF NOT EXISTS `homework_db`.`projects` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework_db`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homework_db`.`companies` ;

CREATE TABLE IF NOT EXISTS `homework_db`.`companies` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework_db`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homework_db`.`customers` ;

CREATE TABLE IF NOT EXISTS `homework_db`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework_db`.`developers_has_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homework_db`.`developers_has_skills` ;

CREATE TABLE IF NOT EXISTS `homework_db`.`developers_has_skills` (
  `developers_developer_id` INT NOT NULL,
  `skills_skill_id` INT NOT NULL,
  PRIMARY KEY (`developers_developer_id`, `skills_skill_id`),
  INDEX `fk_developers_has_skills_skills1_idx` (`skills_skill_id` ASC),
  INDEX `fk_developers_has_skills_developers_idx` (`developers_developer_id` ASC),
  CONSTRAINT `fk_developers_has_skills_developers`
    FOREIGN KEY (`developers_developer_id`)
    REFERENCES `homework_db`.`developers` (`developer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developers_has_skills_skills1`
    FOREIGN KEY (`skills_skill_id`)
    REFERENCES `homework_db`.`skills` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework_db`.`Projects_has_developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homework_db`.`projects_has_developers` ;

CREATE TABLE IF NOT EXISTS `homework_db`.`projects_has_developers` (
  `projects_project_id` INT NOT NULL,
  `developers_developer_id` INT NOT NULL,
  PRIMARY KEY (`projects_project_id`, `developers_developer_id`),
  INDEX `fk_projects_has_developers_developers1_idx` (`developers_developer_id` ASC),
  INDEX `fk_projects_has_developers_projects1_idx` (`projects_project_id` ASC),
  CONSTRAINT `fk_projects_has_developers_projects1`
    FOREIGN KEY (`projects_project_id`)
    REFERENCES `homework_db`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_developers_developers1`
    FOREIGN KEY (`developers_developer_id`)
    REFERENCES `homework_db`.`developers` (`developer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework_db`.`companies_has_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homework_db`.`companies_has_projects` ;

CREATE TABLE IF NOT EXISTS `homework_db`.`companies_has_projects` (
  `companies_company_id` INT NOT NULL,
  `projects_project_id` INT NOT NULL,
  PRIMARY KEY (`companies_company_id`, `projects_project_id`),
  INDEX `fk_companies_has_projects_projects1_idx` (`projects_project_id` ASC),
  INDEX `fk_companies_has_projects_companies1_idx` (`companies_company_id` ASC),
  CONSTRAINT `fk_companies_has_projects_companies1`
    FOREIGN KEY (`companies_company_id`)
    REFERENCES `homework_db`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_projects_projects1`
    FOREIGN KEY (`projects_project_id`)
    REFERENCES `homework_db`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework_db`.`customers_has_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homework_db`.`customers_has_projects` ;

CREATE TABLE IF NOT EXISTS `homework_db`.`customers_has_projects` (
  `customers_customer_id` INT NOT NULL,
  `projects_project_id` INT NOT NULL,
  PRIMARY KEY (`customers_customer_id`, `projects_project_id`),
  INDEX `fk_customers_has_projects_projects1_idx` (`projects_project_id` ASC),
  INDEX `fk_customers_has_projects_customers1_idx` (`customers_customer_id` ASC),
  CONSTRAINT `fk_customers_has_projects_customers1`
    FOREIGN KEY (`customers_customer_id`)
    REFERENCES `homework_db`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_has_projects_projects1`
    FOREIGN KEY (`projects_project_id`)
    REFERENCES `homework_db`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
